before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/mechanic
    id: mechanic
    binary: mechanic
    goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/Carbonfrost/mechanic/internal/build.Version={{.Version}}

archives:
  - id: mechanic
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: mechanic
    ids:
    - mechanic
    tap:
      owner: Carbonfrost
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: "Markdown processing and rendering"
    homepage: "https://github.com/Carbonfrost/mechanic"

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-dev"
